version: 1

info:
  id: groovy
  name: Groovy
  description: |
    <p>Apache Groovy is a Java-syntax-compatible object-oriented programming language for the Java platform. It is both a static and dynamic language with features similar to those of Python, Ruby, and Smalltalk.</p>

  tags:
    - Java
    - MicroProfile
    - Maven

  notes:
    - heading: "Features"
      content: |
        Java 11<br />
        MongoDB<br />
        Automatic TLS certificates<br />
        Maven-based build<br />

initialize:
  repository: git://github.com/platformsh-examples/groovy.git@master
  config: null
  files: []
  profile: Spring
